
/* IMAGES
users.png
drivers.png
cars.png
travels.png   */
DROP TABLE IF EXISTS MAINTENANCES;
DROP TABLE IF EXISTS ACTIVE_DRIVERS;
DROP TABLE IF EXISTS MAINTENANCE_TYPES;

-- task 1 --

CREATE TABLE MAINTENANCE_TYPES (

MAINTENANCE_TYPE_ID CHAR(5) PRIMARY KEY,
MAINTENANCE_TYPE_DESCRIPTION VARCHAR(30) NOT NULL

);

/*
DESCRIBE MAINTENANCE_TYPES
*/

-- task 2 --

CREATE TABLE MAINTENANCES (

CAR_ID CHAR(5),
MAINTENANCE_TYPE_ID CHAR(5),
MAINTENANCE_DUE DATE,

PRIMARY KEY (CAR_ID, MAINTENANCE_TYPE_ID, MAINTENANCE_DUE),
FOREIGN KEY (CAR_ID)
  REFERENCES MAINTENANCE_TYPES(MAINTENANCE_TYPE_ID)

);

/*
DESCRIBE MAINTENANCES;
*/

-- task 3 --

CREATE TABLE ACTIVE_DRIVERS AS

    SELECT
        DRIVER_ID,
        DRIVER_FIRST_NAME,
        DRIVER_LAST_NAME,
        DRIVER_DRIVING_LICENSE_ID,
        DRIVER_DRIVING_LICENSE_CHECKED,
        DRIVER_RATING
    FROM DRIVERS
    WHERE DRIVER_RATING > 0;

ALTER TABLE ACTIVE_DRIVERS ADD PRIMARY KEY (DRIVER_ID);

/*
DESCRIBE ACTIVE_DRIVERS;
*/

-- task 4 --

ALTER TABLE ACTIVE_DRIVERS MODIFY DRIVER_FIRST_NAME VARCHAR(20);
ALTER TABLE ACTIVE_DRIVERS MODIFY DRIVER_LAST_NAME VARCHAR(20);
ALTER TABLE ACTIVE_DRIVERS MODIFY DRIVER_DRIVING_LICENSE_ID VARCHAR(10);

CREATE INDEX NameSearch
  ON ACTIVE_DRIVERS (
    DRIVER_FIRST_NAME,
    DRIVER_LAST_NAME,
    DRIVER_DRIVING_LICENSE_ID
  );

  -- task 5 --

ALTER TABLE ACTIVE_DRIVERS ADD CONSTRAINT DuplicateCheck UNIQUE (DRIVER_FIRST_NAME, DRIVER_LAST_NAME, DRIVER_DRIVING_LICENSE_ID);

-- task 6 --

ALTER TABLE MAINTENANCE_TYPES ADD MAINTENANCE_PRICE FLOAT;