DROP TABLE IF EXISTS EMP_1;

CREATE TABLE EMP_1 (
    EMP_NUM varchar(3) NOT NULL,
    EMP_LNAME varchar(15) NOT NULL,
    EMP_FNAME varchar(15) NOT NULL,
    EMP_INITIAL varchar(1),
    EMP_HIREDATE date,
    JOB_CODE varchar(3),
    PRIMARY KEY (EMP_NUM),
    FOREIGN KEY (JOB_CODE) REFERENCES JOB(JOB_CODE)
);

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('101', 'News', 'John', 'G', '2000-11-08', '502')
;

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('102', 'Senior', 'David', 'H', '1989-07-12', '501')
;

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('103', 'Arbough', 'June', 'E', '1996-12-01', '500')
;

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('104', 'Ramoras', 'Anne', 'K', '1987-11-15', '501')
;

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('105', 'Johnson', 'Alice', 'K', '1993-02-01', '502')
;

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('106', 'Smithfield', 'William', NULL, '2004-06-22', '500')
;

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('107', 'Alonzo', 'Maria', 'D', '1993-10-10', '500')
;

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('108', 'Washington', 'Ralph', 'B', '1991-08-22', '501')
;

INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
    VALUES ('109', 'Smith', 'Larry', 'W', '1997-07-18', '501')
;

UPDATE EMP_1
    SET JOB_CODE = '501'
    WHERE EMP_NUM = '107'
;

DELETE FROM EMP_1
    WHERE
            EMP_LNAME = 'Smithfield'
        AND EMP_FNAME = 'William'
        AND EMP_HIREDATE = '2004-06-22'
        AND JOB_CODE = '500'
;
